import type { Character, RpMessage, Scene } from './types';
import { createSkillMap } from './cocSkills';

const demoStats = {
  str: 10,
  con: 11,
  siz: 12,
  int: 14,
  pow: 13,
  dex: 12,
  app: 11,
  edu: 15,
};

const demoBackground = {
  description: '',
  ideology: '',
  significantPeople: '',
  meaningfulLocations: '',
  treasuredPossessions: '',
  traits: '',
  injuries: '',
  phobias: '',
  tomes: '',
  encounters: '',
};

export const demoCharacters: Character[] = [
  {
    id: 'ren',
    name: '蓮',
    ownerId: null,
    player: 'Hinata',
    archetype: '私立探偵',
    color: '#000000',
    memo: '表向きは酒場の常連。相手の嘘に気づいても、すぐには指摘しない。',
    occupation: '私立探偵',
    age: '32',
    gender: '男性',
    residence: '東京',
    birthplace: '横浜',
    characteristics: demoStats,
    skills: createSkillMap(demoStats, { 目星: 65, 聞き耳: 55, 図書館: 60, 心理学: 45, 説得: 50 }),
    weapons: 'こぶし 50%, 拳銃 40%',
    possessions: '手帳、万年筆、古い鍵',
    background: demoBackground,
    sanityCurrent: 65,
    hitPointsCurrent: 12,
    magicPointsCurrent: 13,
    isArchived: false,
  },
  {
    id: 'mira',
    name: 'ミラ',
    ownerId: null,
    player: 'Guest',
    archetype: '古物研究家',
    color: '#1D4ED8',
    memo: '古い予言を追っている。丁寧語だが、核心では強く踏み込む。',
    occupation: '古物研究家',
    age: '28',
    gender: '女性',
    residence: '京都',
    birthplace: '長崎',
    characteristics: { ...demoStats, int: 16, edu: 17, pow: 14 },
    skills: createSkillMap(
      { ...demoStats, int: 16, edu: 17, pow: 14 },
      { 目星: 55, 図書館: 75, 歴史: 65, オカルト: 70, ほかの言語: 45 },
    ),
    weapons: '杖 35%',
    possessions: '星図、古書、白手袋',
    background: demoBackground,
    sanityCurrent: 70,
    hitPointsCurrent: 12,
    magicPointsCurrent: 14,
    isArchived: false,
  },
  {
    id: 'gm',
    name: '語り手',
    ownerId: null,
    player: 'GM',
    archetype: '進行',
    color: '#666666',
    memo: '場面描写、NPC、判定結果を担当する。',
    occupation: 'NPC',
    age: '',
    gender: '',
    residence: '',
    birthplace: '',
    characteristics: demoStats,
    skills: createSkillMap(demoStats),
    weapons: '',
    possessions: '',
    background: demoBackground,
    sanityCurrent: 65,
    hitPointsCurrent: 12,
    magicPointsCurrent: 13,
    isArchived: false,
  },
];

export const demoScenes: Scene[] = [
  {
    id: 'tavern',
    title: '夜明け前の酒場',
    status: 'active',
    summary: '雨音が屋根を打つ。閉店後の酒場に、まだ灯りがひとつ残っている。',
  },
  {
    id: 'archive',
    title: '港の倉庫街',
    status: 'paused',
    summary: '前回、黒い封蝋の手紙が発見された。',
  },
];

export const demoMessages: RpMessage[] = [
  {
    id: 'm1',
    characterId: 'gm',
    author: '語り手',
    mode: 'ic',
    body: '雨は弱まらない。窓の外で馬車の車輪が軋み、店主は無言で奥の扉を指した。',
    createdAt: '23:41',
  },
  {
    id: 'm2',
    characterId: 'ren',
    author: '蓮',
    mode: 'ic',
    body: '「こんな時間に客を残す店じゃない。奥にいるのは、俺たちを待ってた奴か？」',
    createdAt: '23:43',
  },
  {
    id: 'm3',
    characterId: 'mira',
    author: 'ミラ',
    mode: 'ic',
    body: '「星の位置が変です。ここで会うべき相手は、たぶん一人ではありません」',
    createdAt: '23:44',
  },
  {
    id: 'm4',
    characterId: null,
    author: 'Hinata',
    mode: 'ooc',
    body: '次の返答で奥の扉を開ける流れにして大丈夫です。',
    createdAt: '23:45',
  },
];
