import type { Character, Room, RpMessage, Scene } from './types';
import { createSkillMap } from './cocSkills';

const demoStats = {
  str: 10,
  con: 11,
  siz: 12,
  int: 14,
  pow: 13,
  dex: 12,
  app: 11,
  edu: 15,
};

const demoBackground = {
  description: '',
  ideology: '',
  significantPeople: '',
  meaningfulLocations: '',
  treasuredPossessions: '',
  traits: '',
  injuries: '',
  phobias: '',
  tomes: '',
  encounters: '',
  customMemos: [],
};

export const demoCharacters: Character[] = [
  {
    id: 'ren',
    name: '蓮',
    ownerId: null,
    player: 'Hinata',
    archetype: '私立探偵',
    color: '#000000',
    memo: '表向きは酒場の常連。相手の嘘に気づいても、すぐには指摘しない。',
    occupation: '私立探偵',
    age: '32',
    gender: '男性',
    height: '178cm',
    weight: '68kg',
    hairColor: '黒',
    eyeColor: '茶',
    skinColor: '普通',
    residence: '東京',
    birthplace: '横浜',
    imagePath: '',
    imageUrl: '',
    tags: ['探偵'],
    characteristics: demoStats,
    skills: createSkillMap(demoStats, { 目星: 65, 聞き耳: 55, 図書館: 60, 心理学: 45, 説得: 50 }),
    weapons: 'こぶし 50%, 拳銃 40%',
    possessions: '手帳、万年筆、古い鍵',
    background: demoBackground,
    sanityCurrent: 65,
    hitPointsCurrent: 12,
    magicPointsCurrent: 13,
    isArchived: false,
  },
  {
    id: 'mira',
    name: 'ミラ',
    ownerId: null,
    player: 'Guest',
    archetype: '古物研究家',
    color: '#1D4ED8',
    memo: '古い予言を追っている。丁寧語だが、核心では強く踏み込む。',
    occupation: '古物研究家',
    age: '28',
    gender: '女性',
    height: '164cm',
    weight: '52kg',
    hairColor: '黒',
    eyeColor: '青',
    skinColor: '白',
    residence: '京都',
    birthplace: '長崎',
    imagePath: '',
    imageUrl: '',
    tags: ['研究家'],
    characteristics: { ...demoStats, int: 16, edu: 17, pow: 14 },
    skills: createSkillMap(
      { ...demoStats, int: 16, edu: 17, pow: 14 },
      { 目星: 55, 図書館: 75, 歴史: 65, オカルト: 70, ほかの言語: 45 },
    ),
    weapons: '杖 35%',
    possessions: '星図、古書、白手袋',
    background: demoBackground,
    sanityCurrent: 70,
    hitPointsCurrent: 12,
    magicPointsCurrent: 14,
    isArchived: false,
  },
  {
    id: 'gm',
    name: '語り手',
    ownerId: null,
    player: 'GM',
    archetype: '進行',
    color: '#666666',
    memo: '場面描写、NPC、判定結果を担当する。',
    occupation: 'NPC',
    age: '',
    gender: '',
    height: '',
    weight: '',
    hairColor: '',
    eyeColor: '',
    skinColor: '',
    residence: '',
    birthplace: '',
    imagePath: '',
    imageUrl: '',
    tags: ['進行'],
    characteristics: demoStats,
    skills: createSkillMap(demoStats),
    weapons: '',
    possessions: '',
    background: demoBackground,
    sanityCurrent: 65,
    hitPointsCurrent: 12,
    magicPointsCurrent: 13,
    isArchived: false,
  },
];

export const demoRooms: Room[] = [
  {
    id: 'room-demo',
    title: '夜明け前の酒場',
    summary: '雨の街を舞台にした導入ルーム。酒場、港、古い倉庫が主な探索範囲。',
    tags: ['導入', '1920s', '雨'],
    createdBy: 'demo-user',
  },
];

export const demoScenes: Scene[] = [
  {
    id: 'tavern',
    roomId: 'room-demo',
    createdBy: 'demo-user',
    title: '夜明け前の酒場',
    status: 'active',
    summary: '雨音が屋根を打つ。閉店後の酒場に、まだ灯りがひとつ残っている。',
    locationName: '酒場',
    timeLabel: '深夜',
    mapX: 35,
    mapY: 42,
    tags: ['導入', '屋内'],
    createdAt: '2026-05-14T14:30:00.000Z',
  },
  {
    id: 'archive',
    roomId: 'room-demo',
    createdBy: 'demo-guest',
    title: '港の倉庫街',
    status: 'paused',
    summary: '前回、黒い封蝋の手紙が発見された。',
    locationName: '港の倉庫街',
    timeLabel: '翌朝',
    mapX: 68,
    mapY: 66,
    tags: ['探索', '屋外'],
    createdAt: '2026-05-14T14:40:00.000Z',
  },
];

export const demoMessages: RpMessage[] = [
  {
    id: 'm1',
    characterId: 'gm',
    authorId: 'demo-gm',
    author: '語り手',
    mode: 'ic',
    body: '雨は弱まらない。窓の外で馬車の車輪が軋み、店主は無言で奥の扉を指した。',
    createdAt: '23:41',
  },
  {
    id: 'm2',
    characterId: 'ren',
    authorId: 'demo-user',
    author: '蓮',
    mode: 'ic',
    body: '「こんな時間に客を残す店じゃない。奥にいるのは、俺たちを待ってた奴か？」',
    createdAt: '23:43',
  },
  {
    id: 'm3',
    characterId: 'mira',
    authorId: 'demo-guest',
    author: 'ミラ',
    mode: 'ic',
    body: '「星の位置が変です。ここで会うべき相手は、たぶん一人ではありません」',
    createdAt: '23:44',
  },
  {
    id: 'm4',
    characterId: null,
    authorId: 'demo-user',
    author: 'Hinata',
    mode: 'ooc',
    body: '次の返答で奥の扉を開ける流れにして大丈夫です。',
    createdAt: '23:45',
  },
];
